# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3124494b0e35b135254ca4b8c0b2bb21915af1300664b4d5fb4a9f0b257460ba4d416082e364a220f65496d57302d6418a10675c6b4954485f0019e2167ecbfb

test:
  secret_key_base: 3331769c968c90a37ec9e22414cdb44043bc59091b2b23fbdb6b3197931aa02ada70a9bbddf549e7fc191438d1f40faf33fc5de48bc99036694f9ac388d44a6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
